name: app_tasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.3 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #flutter pub add flutter_slidable, hive, hive_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1 #--dev despues del flutter pub add
  build_runner: ^2.4.13 #la otra

flutter:
  uses-material-design: true
